### ISSUE TITLE
 the methods or code that generated the picture in README?

### ISSUE THREAD

**Issue by beating-1224** [junhocho/HGCAE#2]

**Comment by junhocho** [comment]
We used plotly.

check this link.

https://plotly.com/python/3d-scatter-plots/

**Comment by beating-1224** [comment]
Thank you for your reply! I am wondering how to get a two-dimensional embedded Visual picture in hyperbolic space?If the network output is directly made to be 2-dimensional, using the tanh activation function, we get an ellipse instead of a circle.
    So could you provide the source codes to create the visualization of embeddings in hyperbolic space if possible? 
    Thank you very much for your kind consideration!

**Comment by junhocho** [comment]
It is visualization of the direct coordination output of 2-dimensional embedding. (It is hard to visualize n-dimensional embdding.)

We did not use any activation **only when training and visualizing the 2-dim embbedding**. Like you said, if we use relu, there will be only 1/4 of poincare disk.
